FROM node:18.20.0-alpine3.19 as development

WORKDIR /usr/local/app

RUN chmod 777 -R /usr/local/app

COPY . .

RUN npm install --force

ENV PATH /usr/local/app/node_modules/.bin:$PATH

EXPOSE 4200

CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--poll=2000", "--disable-host-check"]
